config/routes.rb
Rails.application.routes.draw do
  get "sign_up", to: "users#new"
  get "log_in", to: "sessions#new" 
  post "log_in", to: "sessions#create"
  get "log_out", to: "sessions#destroy"

  root :to => "users#new"

  resources :users do
    resources :visits
  end
  resources :sessions
  resources :apps
end

app/models/app.rb
class App < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2 }
  validates :resource_url, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
  validates :password, length: { minimum: 8 }, allow_nil: true
  has_many :visits
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to log_in_url, alert: "Not authorized" if current_user.nil?
    end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :find_app, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  def new
    @app = App.new
  end

  def create
    @app = App.new(app_params)

    if @app.save
      redirect_to @app
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @apps = App.all
  end

  def edit
  end

  def update
    if @app.update(app_params)
      redirect_to @app
    else
      render 'edit'
    end
  end

  def destroy
    @app.destroy

    redirect_to apps_path
  end  

  private
    def find_app
      @app = App.find(params[:id])
    end

    def app_params
      params.require(:app).permit(:name, :resource_url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to apps_path, :notice => "Logged in!"
    else
      flash[:error] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :find_user
  before_action :find_visit, only: [:destroy]
  before_action :authorize

  def create
    count = @user.visits.count
    @visit = @user.visits.where(name: visit_params[:name])
      .first_or_create(visit_params)
    @visit.update(visit_params) if @user.visits.count == count
    redirect_to user_visits_path
  end

  def index
    @visits = @user.visits.order(:time)
  end

  def destroy
    @visit.destroy
    redirect_to user_visits_path
  end 

  private
    def find_user
      @user = User.find(params[:user_id])
    end

    def find_visit
      @visit = @user.visits.find(params[:id])
    end

    def visit_params
      params.require(:visit).permit(:name, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/apps/_form.html.erb
<%= form_for @app do |a| %>
	<% if @app.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@app.errors.count, "error") %>
				stopped this app from being saved:
			</h2>
			<ul>
				<% @app.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= a.label :name %><br>
		<%= a.text_field :name %>
	</p>

	<p>
		<%= a.label :resource_url %><br>
		<%= a.text_area :resource_url %>
	</p>

	<p>
		<%= a.submit %>
	</p>

<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>
 
<table>
  <tr>
    <th>App</th>
  </tr>
 
  <% @apps.each do |app| %>
    <tr>
      <td><%= app.name %></td>
      <td><%= link_to 'Show', app_path(app) %></td>
      <td><%= link_to 'Edit', edit_app_path(app) %></td>
      <td><%= link_to 'Destroy', app_path(app), method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New app', new_app_path %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Apps Index', apps_path %>

app/views/apps/show.html.erb
<p>
	<strong>App name:</strong>
	<%= @app.name %>
	<%= @app.resource_url %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %>
<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>visit_check</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>Visit Check app</header>
<%= yield %>	
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", log_out_path %>
<% else %>
  <%= link_to "Sign Up", sign_up_path %> or
  <%= link_to "Log In", log_in_path %>
<% end %>
    <% flash.each do |key, value| %>
      <div class="<%= key %>"><%= value %></div>
    <% end %>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>
 
<table>
  <tr>
    <th>Visit</th>
  </tr>
 
  <% @visits.each do |visit| %>
    <tr>
      <td><%= visit.name %></td>
      <td><%= visit.time %></td>
      <td><%= link_to 'Destroy', [visit.user, visit], method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>